In [1]:
#importing numpy
import numpy as np
#creating a 1D array
X=np.array([1,2,3,4,5,6,7,8,9,10])
print(X)


[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#creating a 3*3 numpy array of all True's
Y=np.array([[True,True,True],[True,True,True],[True,True,True]],dtype=bool)
Y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
#given an array as input, print only odd numbers as output
X=np.array([1,2,34,46,65,63,34632,1354,234,4323,21,123,132,2323,6687])
list(filter(lambda x:x%2!=0,X))

[1, 65, 63, 4323, 21, 123, 2323, 6687]

In [4]:
#replacing all odd numbers in the array with -2
X=np.array([1,2,3,4,5])
for i in range(0,len(X)):
    if X[i]%2!=0:
        X[i]=-2
print(X)

[-2  2 -2  4 -2]


In [5]:
#how to reshape an array
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#convert a 1d array to a 2d array with 2 rows
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)

In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#given an array, create new array from it such that it includes all odd numbers and 4 multiples
a=np.array([1,2,3,4,5,6,7,8,9])
list(filter(lambda x:x%2!=0 or x%4==0,a))


[1, 3, 4, 5, 7, 8, 9]

In [9]:
#how to replace all missing values with 0 in a numpy array
x=np.array(['india','pakistan','','afghanistan','','nepal'])
for i in range(0,len(x)):
    if x[i]:
        print('Element is found')
    else:
        x[i]=0

Element is found
Element is found
Element is found
Element is found


In [10]:
x

array(['india', 'pakistan', '0', 'afghanistan', '0', 'nepal'],
      dtype='<U11')

In [11]:
x=[1,1,2,2,2,5,5,34,34,34,34]
np.array(np.unique(x,return_counts=True)).T

array([[ 1,  2],
       [ 2,  3],
       [ 5,  2],
       [34,  4]], dtype=int64)

In [12]:
#above to find the count of each unique number in a NumPy array

In [13]:
#program to print all numbers btw 99 and 299 that are divisible by 5 or 7 exclusively
for i in range(99,299):
    if (i%5==0 and i%7==0):
        print("sorry, we cannot print the number")
    elif (i%5==0 or i%7==0):
        print("the number is ",i)

the number is  100
sorry, we cannot print the number
the number is  110
the number is  112
the number is  115
the number is  119
the number is  120
the number is  125
the number is  126
the number is  130
the number is  133
the number is  135
sorry, we cannot print the number
the number is  145
the number is  147
the number is  150
the number is  154
the number is  155
the number is  160
the number is  161
the number is  165
the number is  168
the number is  170
sorry, we cannot print the number
the number is  180
the number is  182
the number is  185
the number is  189
the number is  190
the number is  195
the number is  196
the number is  200
the number is  203
the number is  205
sorry, we cannot print the number
the number is  215
the number is  217
the number is  220
the number is  224
the number is  225
the number is  230
the number is  231
the number is  235
the number is  238
the number is  240
sorry, we cannot print the number
the number is  250
the number is  252
the number is

In [14]:
#wap to reverse and array and print
x=np.array([1,2,3,4,5])
n=len(x) #value of n is 5
for i in range(0,(n-1)//2):
    temp1=x[i]
    temp2=x[n-1-i]
    x[i]=temp2
    x[n-1-i]=temp1

In [15]:
x

array([5, 4, 3, 2, 1])